<!DOCTYPE html>
<html>
    <head>
        <!-- UTF-8 (accents ...) -->
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />

        <!-- on s'assure que le rendu graphique et les entrées soit correctes sur mobile -->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- font awesome icons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- logo du titre de la page -->
        <link rel="shortcut icon" href="./images/favicon.ico" />

        <!-- le titre -->
        <title>ULC</title>

        <!-- css -->
        <link rel="stylesheet" type="text/css" href="./css/aside.css">
        <link rel="stylesheet" type="text/css" href="./css/main.css">
        <link rel="stylesheet" type="text/css" href="./css/navbar.css">
        <link rel="stylesheet" type="text/css" href="./css/notification.css">
        <link rel="stylesheet" type="text/css" href="./css/page.css">
        <link rel="stylesheet" type="text/css" href="./css/sidebar.css">
        <link rel="stylesheet" type="text/css" href="./css/toastbar.css">

        <!-- reCaptcha -->
        <script type="text/javascript" src='https://www.google.com/recaptcha/api.js'></script>

        <!-- style -->
        <script type="text/javascript" src="./js/animation.js"></script>
        <script type="text/javascript" src="./js/disconnect.js"></script>
        <script type="text/javascript" src="./js/utils.js"></script>

        <!-- import du fond animé -->
       <script type="text/javascript" src="https://unpkg.com/delaunator@2.0.0/delaunator.min.js"></script>
       <script type="text/javascript" src="./js/noise.js"></script>
       <script type="text/javascript" src="./js/background.js"></script>


    </head>


    <body onload="onPageLoaded()">
   
   