        <!-- la barre des messages d'informations en bas du site (toast) -->
        <script type="text/javascript">
            var toasts = {};
            var nextToastTime = 0;

            function toast(message, level, duration=2000) {
                if (toasts[message] || duration < 0) {
                    return ;
                }
                toasts[message] = true;
                
                var timer = duration + 500;
                setTimeout(function() {
                    var bar = document.getElementById("toastbar");
                    bar.innerHTML = message;
                    bar.style.visibility = "visible";
                    bar.style.animation = "fadein 0.5s, fadeout 0.5s " + (duration / 1000.0) + "s";

                    var color = (level == 0) ? "error" : (level == 1) ? "warning" : "fine";
                    bar.classList.add(color);

                    setTimeout(function() {
                                bar.style.visibility = "hidden";
                                bar.style.animation  = "";
                                bar.classList.remove(color);
                                nextToastTime -= timer;
                                toasts[message] = null;
                            }, timer);
                }, nextToastTime);
                nextToastTime += timer;
            }
        </script>
        <div id="toastbar">Bienvenue :)</div>