        <!-- la barre des messages d'informations en bas du site (toast) -->
        <div id="toastbar">Bienvenue :)</div>

        <style>
            #toastbar {
                opacity: 0;
                max-width: 20rem;
                min-width: 20rem;
                margin-left: -10rem;
                background-color: #333;
                color: #F1F1F1;
                text-align: center;
                border-radius: 0.3rem;
                padding: 1rem;
                position: fixed;
                z-index: 99;
                left: 50%;
                bottom: 2rem;
            }

            #toastbar.error {
                background-color: #FF2222;
            }

            #toastbar.warning {
                background-color: orange;
                color: orange;
            }

            #toastbar.fine {
                background-color: #22FF22;
            }
        </style>


        <script type="text/javascript">
            var bar = document.getElementById("toastbar");
            var toasts = {};
            var last = Date.now();
            var nextTimeIn = 0;

            function toast(message, level="fine", duration=2.0, fadeLength=0.5) {
                if (toasts[message] || duration < 0) {
                    return ;
                }
                var timeout = Math.max(nextTimeIn - (Date.now() - last), 0);
                var totalDuration = (fadeLength + fadeLength + duration) * 1000;
                nextTimeIn += totalDuration;
                setTimeout( function() {
                                last = Date.now();
                                bar.classList.add(level);
                                bar.innerHTML = message;
                                fadeIn(bar, 30, fadeLength);
                                setTimeout( function() {
                                                fadeOut(bar, 30, fadeLength);
                                                setTimeout( function() {
                                                                toasts[message] = false;
                                                                nextTimeIn -= totalDuration;
                                                            },
                                                            fadeLength * 1000
                                                );
                                            },
                                            (fadeLength + duration) * 1000
                                );
                            },
                            timeout
                );
            }
        </script>
