<?php
use Model\ULC\ULCDiscord;

require ('../vendor/autoload.php');

$client = ULCDiscord::client ();
$members = $client->guild->listGuildMembers ( [ 
		'guild.id' => ULCDiscord::guildID (),
		'limit' => 10 
] );
$membersCount = count ( $members );
var_dump ( $members );
?>


<!-- discord component -->
<div class="discord">

	<!-- header -->
	<div class="discord-header">
		<!-- logo -->
		<div class="discord-header-img"
			onclick="window.open('https://discord.gg/BcsrE47', '_blank')">
			<img src="./images/discord/header.png"></img>
		</div>


		<!-- membres en ligne -->
		<div class="discord-header-title">
			<strong><?php echo $membersCount; ?></strong> Membres en ligne
		</div>

	</div>

	<!-- content -->
	<div class="discord-body">
		<!-- liste des membres en ligne -->
		<div>
			<!-- titre -->
			<div class="discord-body-title">Membres</div>

			<!-- les membres -->
<?php
for($j = 0; $j < 4; $j ++) {
	for($i = 0; $i < $membersCount; $i ++) {
		$user = $members [$i]->user;
		?>
			<div class="discord-body-member">
				<img
					src="https://cdn.discordapp.com/avatars/<?php echo $user->id . '/' . $user->avatar ; ?>.png"></img>
				<?php echo $user->username ; ?>
			</div>
<?php
	}
}
?>
		</div>
	</div>

</div>